"""Add MpesaTransaction table

Revision ID: 022eefba41ab
Revises: 1c6cfa2a7e2c
Create Date: 2025-02-03 12:42:27.557435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022eefba41ab'
down_revision: Union[str, None] = '1c6cfa2a7e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('transaction_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'mpesa_transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mpesa_transactions', type_='unique')
    op.drop_column('mpesa_transactions', 'transaction_id')
    # ### end Alembic commands ###
