"""Recreate migrations

Revision ID: 0c003882c489
Revises: 6c67d8e6cbf1
Create Date: 2025-02-02 11:21:14.756941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c003882c489'
down_revision: Union[str, None] = '6c67d8e6cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('mpesa_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_transactions', 'mpesa_code')
    # ### end Alembic commands ###
