"""Add MpesaTransaction table

Revision ID: 1c6cfa2a7e2c
Revises: 1b814d463e12
Create Date: 2025-02-03 12:26:15.924953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6cfa2a7e2c'
down_revision: Union[str, None] = '1b814d463e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('merchant_request_id', sa.String(length=50), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('result_code', sa.String(length=10), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('mpesa_transactions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('mpesa_transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=True)
    op.alter_column('mpesa_transactions', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_mpesa_transactions_id', table_name='mpesa_transactions')
    op.drop_constraint('mpesa_transactions_transaction_id_key', 'mpesa_transactions', type_='unique')
    op.create_unique_constraint(None, 'mpesa_transactions', ['checkout_request_id'])
    op.drop_column('mpesa_transactions', 'transaction_id')
    op.drop_column('mpesa_transactions', 'mpesa_code')
    op.drop_column('mpesa_transactions', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mpesa_transactions', sa.Column('mpesa_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mpesa_transactions', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mpesa_transactions', type_='unique')
    op.create_unique_constraint('mpesa_transactions_transaction_id_key', 'mpesa_transactions', ['transaction_id'])
    op.create_index('ix_mpesa_transactions_id', 'mpesa_transactions', ['id'], unique=False)
    op.alter_column('mpesa_transactions', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mpesa_transactions', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('mpesa_transactions', 'id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('mpesa_transactions', 'created_at')
    op.drop_column('mpesa_transactions', 'result_code')
    op.drop_column('mpesa_transactions', 'transaction_date')
    op.drop_column('mpesa_transactions', 'checkout_request_id')
    op.drop_column('mpesa_transactions', 'merchant_request_id')
    # ### end Alembic commands ###
