"""Add MpesaTransaction table

Revision ID: c4f527582a7d
Revises: a5bceced8fcc
Create Date: 2025-02-03 13:02:59.024381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f527582a7d'
down_revision: Union[str, None] = 'a5bceced8fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('mpesa_transactions', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('mpesa_transactions_id_seq'::regclass)"))
    op.drop_constraint('mpesa_transactions_transaction_id_key', 'mpesa_transactions', type_='unique')
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=True)
    op.drop_column('mpesa_transactions', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('transaction_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.create_unique_constraint('mpesa_transactions_transaction_id_key', 'mpesa_transactions', ['transaction_id'])
    op.alter_column('mpesa_transactions', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('mpesa_transactions_id_seq'::regclass)"))
    op.drop_column('mpesa_transactions', 'updated_at')
    # ### end Alembic commands ###
